spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/vroom?characterEncoding=UTF-8&serverTimezone=UTC
    username :
    password :

  jpa:
    open-in-view: true #OSIV 설정
    hibernate:
      ddl-auto: create #create
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MariaDBDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정
        format_sql: true
        use_sql_comments: true  # Querydsl JPQL 변환될 떄  JPQL 쿼리 로그 보는 설정
        default_batch_fetch_size: 100
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor # import.sql 테스트 데이터 제거시 같이 제거
    defer-datasource-initialization: true # import.sql 테스트 데이터 제거시 같이 제거

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  api-docs:
    enabled: true # Springdoc-openAPI 사용 여부
  swagger-ui:
    enabled: true # Swagger-ui 사용 여부
    tagsSorter: alpha # Tag의 정렬 기준 (alpha => 알파벳 정렬)
    operations-sorter: alpha # Swagger-ui에서 각 API에 대한 정렬 기준 (alpha => 알파벳 정렬)
    display-request-duration: true #Swagger-ui에서 API 실행 시 처리 소요 시간 표시 여부



logging.level:
  org.hibernate.SQL: debug